#page title
page_title                                : Sunrides                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Sunrides                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Sunrides provides quick and easy trip planning around El Paso using public transit. Get access to bus stop locations, schedules, and route maps even while offline. Sunrides also includes live BCycle station feeds to help plan your next trip.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Isaac Diaz                                
your_link                                 :                      
your_city                                 : El Paso                                
email_address                             : isaacd.ce@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : isaacd
github_username                           : isaacdce
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Trip Planning
    description                           : Get directions to help navigate around El Paso using the public transit system.
    fontawesome_icon_name                 : route
    
  - title                                 : Bus Stop Information
    description                           : Look up bus stops around you and check departure times for each route.
    fontawesome_icon_name                 : bus

  - title                                 : Route Maps
    description                           : Scroll through color-coded routes for a map of stops and scheduled departures.
    fontawesome_icon_name                 : map

  - title                                 : BCycle Stations
    description                           : Switch on BCycle station markers to get live info on available bikes and open docks.
    fontawesome_icon_name                 : map-marker-alt


  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/epnightscape.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#00000000"
cover_overlay_transparency                : 0.5

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#2b2b2e"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#46ccff"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
